#!/bin/bash

<<info
       loop: anything that you want to repeat again and again and again based on Condations
 1..10
       start point=1
      ending point=10
      increment/decrement= +/-
5...1
info
for((num=1;num<=10;num++))
  do
     echo "$num"
     echo "Hello bro"
 done
